name: TDCannon
favicon: null
layout_spectrum: 0.6478839
typography_spectrum: 0.7568533
title: TD Cannon
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.05471677
  lightness: 0.851776
  saturation: 0.3282133
  rhythmicContrast: 0.2496781
purpose: []
